config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  concern :votable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable] do
      member do
        post :best
      end
    end
  end

  root to: "questions#index"
  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  def best_answer
    answers.find_by(best: true)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: [:new, :create]
  before_action :find_question, only: [:show, :update, :destroy]
  before_action :check_user, only: [:update, :destroy]
  after_action :publish_question, only: [:create]

  def index
    @questions = Question.all 
  end
  
  def show
    @answer = Answer.new
    @answers = @question.answers.sorted_best
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_reward
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new, question: @question
    end
  end

  def update
    @question.update(question_params) 
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Your question successfully destroyed.'
  end

  private

  def find_question
    @question = Question.with_attached_files.find(params[:id])
    gon.question_id = @question.id
    gon.question_user_id = @question.user_id
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:name, :url], reward_attributes: [:name, :file])
  end

  def check_user
    unless current_user.author_of?(@question)
      redirect_to root_path, notice: 'Access denied'
    end
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast('questions', question: @question)
  end
end

app/views/questions/_question.html.slim
div class="question_#{question.id}"
  p =question.title
  p =question.body

  - if current_user&.author_of?(question)
    - if question.reward.present?
      p= question.reward.name
    p= link_to 'Edit', '#', class: 'edit-question-link', data: { question_id: question.id }
    p= link_to 'Destroy', question_path(question), method: :delete, remote: true

  - if question.files.attached?
    p Files:
    - question.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      - if current_user&.author_of?(question)
        p= link_to 'Destroy file', file_path(file), method: :delete  

  - if question.links.any?
    .links
      p Links:
      ul
        - question.links.each do |link|
          li
            - if gist?(link)
              script src="#{link.url}.js"
            - else
              = link_to link.name, link.url
          - if current_user&.author_of?(question)
            span= link_to 'Destroy link', link_path(link), method: :delete

  .question_votes
    - if current_user && !current_user&.author_of?(question)
      .question_like
        => link_to 'Up!', polymorphic_path(question, action: :like), method: :post, remote: true, data: { type: :json }
        .question_rating
          b= question.rating
        => link_to 'Down', polymorphic_path(question, action: :dislike), method: :post, remote: true, data: { type: :json }     

  div class="question-#{question.id}-errors"    

  = form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
    = f.label :title
    = f.text_field :title
    = f.label :body
    = f.text_area :body
    p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
    p
      = f.fields_for :links do |l|
      = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields'
    = f.submit 'Save'

app/views/questions/index.html.slim
br
p = link_to 'Ask question', new_question_path

h3 Questions list

table.table.table-striped
  thead
    tr
      th
        | Вопрос
      th colspan="3"
  tbody.questions-list
    - @questions.each do |question|
      tr
        td= question.title
        td
          button.btn.btn-link type="button"
            = link_to 'show', question_path(question)
          - if current_user&.author_of?(question)
            button.btn.btn-link type="button"
              = link_to 'destroy', question_path(question), method: :delete

app/views/questions/new.html.slim
.row
  .col-xs-6
    = form_with model: @question,  local: true do |f|
      = render 'layouts/errors', resource: @question
      .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control'

      .form-group
        = f.label :body
        = f.text_area :body, class: 'form-control'

      .form-group
        = f.label :files
        = f.file_field :files, multiple: true, direct_upload: true

      p Reward
      p
      = f.fields_for :reward do |reward_f|
        .form-group
        = reward_f.label :name
        = reward_f.text_field :name, class: 'form-control'
        .form-group
        = reward_f.label :file, 'Image'
        = reward_f.file_field :file, direct_upload: true

      p Links:
      p
        = f.fields_for :links do |l|
        = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields'

      .actions.form-group
        .col-sm-10
          = f.submit 'Ask', class: 'btn btn-success'
          button.btn.btn-link type="button" 
            = link_to 'Back', questions_path

app/views/questions/show.html.slim
.questions
  = render @question

.question_comments
  - if user_signed_in?
    = link_to 'Add comment', '', class: 'add-comment-link', data: {resource_id: @question.id, resource_type: 'question'}
    = render 'comments/form', resource: @question

  - if @question.comments.size > 1
    h4= 'Comments:'
    = render @question.comments  

br
h5 Answers
.answers 
  = render @question.answers

- if user_signed_in?
  div
    h6
      | Create Answer
    .answer-errors
      = render partial: 'layouts/errors', locals: { resource: @answer }
    .answer-form
      = form_with model: [@question, @answer], class: 'new-answer', data: {type: :json} do |f|

        .form-group
          = f.label :body, 'Your answer'
          = f.text_field :body, class: 'form-control'

        .form-group
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true

        p Links:
        p
          = f.fields_for :links do |l|
          = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields'

        .actions.form-group
          .col-sm-10
            = f.submit 'Reply', class: 'btn btn-success'

app/views/questions/update.js.erb
$('.question-<%= @question.id %>-errors').html('<%= render 'layouts/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question_<%= @question.id %>').html('<%= j render @question %>');
<% end %>