config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  concern :votable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable] do
      member do
        post :best
      end
    end
  end

  root to: "questions#index"
  mount ActionCable.server => '/cable'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_resource, only: :create
  before_action :find_comment, only: [:update, :destroy]
  after_action :publish_comment, only: :create

  def create
    @comment = @resource.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
  end

  def update
    @comment.update(comment_params) if current_user.author_of?(@comment)
  end

  def destroy
    @comment.destroy if current_user.author_of?(@comment)
  end

  private

  def find_resource
    if params[:answer_id]
      @resource = Answer.find(params[:answer_id])
    else
      @resource = Question.find(params[:question_id])
    end
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end

  def publish_comment
    return if @comment.errors.any?
    question_id = @resource.is_a?(Question) ? @resource.id : @resource.question.id
    ActionCable.server.broadcast("comments_question_#{question_id}", comment: @comment)
  end
end

app/views/comments/_comment.html.slim
- if comment.persisted?
  div class="comment_#{comment.id}"
    p= comment.body
    - if current_user&.author_of?(comment)
      => link_to 'Edit', '', class: 'edit-comment-link', data: {comment_id: comment.id}
      = form_for comment, remote: true, html: {id: "edit-comment-#{comment.id}"} do |f|
        span.errors
        p= f.label :body, 'Comment'
        p= f.text_area :body, class: 'edit_comment_text_area'
        p= f.submit 'Save'
      = link_to 'Delete', comment_path(comment), method: :delete, remote: true
      

app/views/comments/_form.html.slim
- resource_type = resource.class.name.underscore

= form_with model: [resource, resource.comments.new], remote: true,
        class: 'new_comment',
        id: "new-comment-#{resource_type}-#{resource.id}"do |f|
  span.errors
  p= f.label :body, 'Comment'
  p= f.text_area :body, class: 'new_comment_text_area'
  p= f.submit 'Comment'
  = link_to 'Hide', '', class: 'hide-comment-link', data: { resource_id: resource.id, resource_type: resource_type }

app/views/comments/create.js.erb
<% resource_type = @comment.commentable_type.underscore %>
<% resource_id = @comment.commentable_id %>

<% if @comment&.errors.present? %>
errors = $('form#new-comment-<%= resource_type %>-<%= resource_id %>').find('.errors');
errors.html('<%= j render partial: 'layouts/errors', locals: { model: @comment } %>');
<% else %>
<% if resource_type == 'question'%>
$('.question_comments').append('<%= j render @comment %>');
<% else %>
$('.answer_<%= resource_id %>').find('.answer_comments').append('<%= j render @comment %>');
<% end %>
$('.new_comment_text_area').val('');
$('#new-comment-<%= resource_type %>-<%= resource_id %>').hide()
$('.add-comment-link').show();
<% end %> 

app/views/comments/destroy.js.erb
$('.comment_<%= @comment.id %>').remove();

app/views/comments/update.js.erb
<% if @comment&.errors.present? %>
errors = $('form#edit-comment-<%= @comment.id %>').find('.errors');
errors.html('<%= j render partial: 'layouts/errors', locals: { model: @comment } %>');
<% else %>
$('.comment_<%= @comment.id %>').html('<%= j render @comment %>');
<% end %>