config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  concern :votable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable] do
      member do
        post :best
      end
    end
  end

  root to: "questions#index"
  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  
  belongs_to :question
  belongs_to :user
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  
  validates :body, presence: true

  scope :sorted_best, -> { order(best: :desc) }

  def make_best
    ActiveRecord::Base.transaction do
      old_best_answer = question.best_answer
      old_best_answer.update!(best: false) if old_best_answer
      update!(best: true)
      send_reward
    end
  end

  def send_reward
    question.reward&.update!(user: user)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: [ :create ]
  before_action :find_question, only: [:create]
  before_action :find_answer, only: [:update, :best, :destroy]
  before_action :check_user, only: [:update,  :destroy]
  before_action :question_owner, only: [:best]
  after_action :publish_answer, only: [:create]
  
  def create
    @answer = @question.answers.create(answer_params.merge(user: current_user))
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    @answer.destroy
  end

  def best
    @question = @answer.question
    @answer.make_best
  end
  
  private
  
  def find_question
    @question = Question.find(params[:question_id])
  end
  
  def find_answer
    @answer = params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
  end
  
  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def check_user
    unless current_user.author_of?(@answer)
      redirect_to root_path, notice: 'Access denied'
    end
  end

  def question_owner
    unless current_user.author_of?(@answer.question)
      redirect_to root_path, notice: 'Access denied'
    end
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
        "answers_question_#{@question.id}",
        answer: @answer,
        links: @answer.links,
        rating: @answer.rating
    )
  end
end

app/views/answers/_answer.html.slim
div class="answer_#{answer.id}"
  span> =answer.body

  - if answer.best?
    b= '- Best answer! '

  - if current_user&.author_of?(answer)
    span> =link_to 'Edit Answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    span> =link_to 'Destroy Answer', answer_path(answer), method: :delete, remote: true

  - if current_user&.author_of?(answer.question) && !answer.best? && !current_user&.author_of?(answer)
    span> =link_to 'Make best', best_answer_path(answer), method: :post, remote: true, class: 'best-answer-link'

  .answer_votes
    - if current_user && !current_user&.author_of?(answer)
      .answer_like
        => link_to 'Up!', polymorphic_path(answer, action: :like), method: :post, remote: true, data: { type: :json }
        div class="answer_rating_#{answer.id}"
          b= answer.rating 
        => link_to 'Down', polymorphic_path(answer, action: :dislike), method: :post, remote: true, data: { type: :json }

  .answer_comments
    - if user_signed_in?
      => link_to 'Add comment', '', class: 'add-comment-link', data: {resource_id: answer.id, resource_type: 'answer'}
      = render 'comments/form', resource: answer
    - if answer.comments.size > 1
      h4= 'Comments:'
      = render answer.comments  

  .links
    p Links:
    ul
      - answer.links.each do |link|
        li= link_to link.name, link.url
        - if current_user&.author_of?(answer)
          span= link_to 'Destroy answer link', link_path(link), method: :delete

  - if answer.files.attached?
    p Files:
    - answer.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
      - if current_user&.author_of?(answer)
        p= link_to 'Destroy answer file', file_path(file), method: :delete

  div class="answer-#{answer.id}-errors"    

  = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
    = f.label :body, 'Your answer'
    = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
    p
      = f.fields_for :links do |l|
      = link_to_add_association 'Add link', f, :links, partial: 'links/link_fields'
    = f.submit 'Save'
  

app/views/answers/best.js.erb
$('.answers').html('<%= j render @question.answers.sorted_best %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'layouts/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %> 

app/views/answers/destroy.js.erb
$('.answer_<%= @answer.id %>').remove();

app/views/answers/update.js.erb
$('.answer-<%= @answer.id %>-errors').html('<%= render 'layouts/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answer_<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>