config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :files, only: :destroy
  resources :links, only: :destroy
  resources :rewards, only: :index

  concern :votable do
    member do
      post :like
      post :dislike
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :update, :destroy], shallow: true
  end

  resources :questions, concerns: [:votable, :commentable] do
    resources :answers, shallow: true, concerns: [:votable, :commentable] do
      member do
        post :best
      end
    end
  end

  root to: "questions#index"
  mount ActionCable.server => '/cable'
end

app/views/layouts/_errors.html.slim
- if resource&.errors.present?
  .alert.alert-error
    a.close data-dismiss="alert"
     | &#215;
    ul
      - resource.errors.full_messages.each do |msg|
        = content_tag :li, msg, :id => "error_#{msg}"

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light style="background-color: #71da71;"
  = link_to 'Stackoverflow', root_path, class: "navbar-brand"
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    ul.navbar-nav
      - if current_user
        li.nav-item = link_to 'Questions', questions_path, class: "nav-link"
        li.nav-item = link_to 'Rewards', rewards_path, class: "nav-link"
        li.nav-item = link_to 'Add question', new_question_path, class: "nav-link"   
      - else
        li = link_to 'Signup', new_user_registration_path, class: "nav-link"   
        li = link_to 'Login', new_user_session_path, class: "nav-link" 
    ul.nav.navbar-nav.ml-auto
      - if current_user
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button"
            = current_user.email
              span.caret
          ul.dropdown-menu
            li = link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link"       
          

app/views/layouts/application.html.slim
doctype html
html
  head
    title Stackoverflow
    = Gon::Base.render_data
    = csrf_meta_tags
    = csp_meta_tag
    = action_cable_meta_tag
    
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/header'
    div.container
      - if notice
        .alert.alert-primary role="alert" = notice
      - if alert  
        .alert.alert-danger role="alert" = alert
      = yield